name: Deploy hello.py into cct_workflow

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Commit message'
        default: 'New commit'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment package for cct_workflow_test function
        run: |
          cd app
          zip -r9 lambda.zip .

      - name: Deploy cct_workflow_test function
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            FUNCTION_NAME=${{ secrets.AWS_PROD_FUNCTION_NAME }}
            ENVIRONMENT="Production"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            FUNCTION_NAME=${{ secrets.AWS_DEV_FUNCTION_NAME }}
            ENVIRONMENT="Development"
          else
            echo "Error: This workflow only supports deployments on dev and main branches."
            exit 1
          fi

          echo "Deploying to $ENVIRONMENT environment..."

          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://app/lambda.zip \
            --publish \
            --cli-input-json "$(cat <<EOF
            {
              "Description": "${{ inputs.description }}"
            })


          echo "Deployment to $ENVIRONMENT completed successfully."
